In [1]:
import numpy as np


In [2]:
# convert temps to Celsius

temperatures_f = np.array([32, 50, 68, 77, 86, 95])

celsius = (temperatures_f - 32) * 5/9
print(celsius)

[ 0. 10. 20. 25. 30. 35.]


In [3]:
# compute std dev and variance
a = np.array([48, 49, 50, 51, 52])
b = np.array([10, 30, 50, 70, 90])

print(a.var())
print(a.std())

2.0
1.4142135623730951


In [4]:
print(b.var())
print(b.std())

800.0
28.284271247461902


In [5]:
X = np.array([
    [3.2, 78, 6],
    [3.8, 94, 9],
    [2.9, 71, 4],
    [3.6, 88, 8]
])

X[:,0]
X.shape

(4, 3)

In [6]:
"""
mean
median
minimum
maximum
standard deviation

"""

names = np.array([
    "Alice",
    "Bob",
    "Charlie",
    "Dana",
    "Ethan",
    "Faith"
])

exam1 = np.array([88, 64, 91, 72, 59, 84])

exam2 = np.array([92, 70, 89, 68, 61, 95])

print(exam1.min())
print(exam1.max())
print(exam1.std())
print(exam1.mean())

passed_exam1 = exam1 >= 70
print(exam1[passed_exam1])

passed_exam2 = exam2 >= 70
print(exam2[passed_exam2])

# print names of students who passed both exams
passed_both = passed_exam1 & passed_exam2
print(names[passed_both])


59
91
12.119772641798562
76.33333333333333
[88 91 72 84]
[92 70 89 95]
['Alice' 'Charlie' 'Faith']


In [7]:
# print averages for each student
exams_averages = (exam1 + exam2) / 2
print(exams_averages)

[90.  67.  90.  70.  60.  89.5]


In [8]:
# find best performer
highest_score = exams_averages.argmax()
print(names[highest_score])

Alice


In [9]:
# find the students whose individual avg exceeds overall student avg

avg = exams_averages.mean()
above_mask = exams_averages > avg
print(names[above_mask])

['Alice' 'Charlie' 'Faith']


In [10]:
# In ML lang: (num of samples, num of features)

X = np.column_stack((exam1, exam2))
print(X.shape)

(6, 2)


In [11]:
"""Module 2, Day 3"""


'Module 2, Day 3'

In [12]:
X = np.array([
    [3.2, 75],
    [3.8, 91],
    [2.9, 68]
])
X.shape


(3, 2)

In [13]:

Y = np.array([
    [2,5,8],
    [4,7,1],
    [6,3,9],
    [8,2,4]
])

In [14]:
Y.shape

(4, 3)

In [15]:
Y.ndim


2

In [16]:
Y.size

12

In [17]:
Y[1,2]

np.int64(1)

In [18]:
Y[0,:]


array([2, 5, 8])

In [19]:
Y[:,1]

array([5, 7, 3, 2])

In [20]:
Y[:2,:2]

array([[2, 5],
       [4, 7]])

In [21]:
Y.sum

<function ndarray.sum>

In [22]:
# this will sum each column
Y.sum(axis=0)

array([20, 17, 22])

In [23]:
# this will sum each row
Y.sum(axis=1)

array([15, 12, 18, 14])

In [24]:
Y.mean(axis=0)

array([5.  , 4.25, 5.5 ])

In [25]:
x = np.array([2,3,4])

w = np.array([5,1,2])

In [26]:
# calculate dot product
np.dot(x,w)

np.int64(21)

In [27]:
# calculate dot product
x @ w

np.int64(21)

In [28]:
# calculate the norm 
v = np.array([3,4])
np.linalg.norm(v)

np.float64(5.0)

In [29]:
# cols are Study Hours and Previous Exam
X = np.array([
    [2,8],
    [5,4],
    [7,9],
    [3,6]
])

# weights
w = np.array([
    0.6,
    0.4
])



In [30]:
# calculate dot product
X @ w

array([4.4, 4.6, 7.8, 4.2])

In [31]:
b = 3
X @ w + b

array([ 7.4,  7.6, 10.8,  7.2])

In [32]:
# cols: Study Hours and Previous Exam
names = np.array([
    "Alice",
    "Bob",
    "Charlie",
    "Dana",
    "Ethan"
])

X = np.array([
    [4,65],
    [7,78],
    [9,92],
    [3,70],
    [8,88]
])

# weights
w = np.array([
    2.5,
    0.7
])

b = 5

In [33]:
# print shape, dimensions, size
X.shape

(5, 2)

In [34]:
X.ndim

2

In [35]:
X.size

10

In [48]:
"""
Using only axis, compute:
Mean study hours
Mean previous exam
Minimum of each feature
Maximum of each feature
Standard deviation of each feature
"""
study_hours_mean = X[:,0].mean(axis=0)
mean_prev_exam = X[:,1].mean(axis=0)
min_of_study_hrs = X[:,0].min()
min_of_prev_exam = X[:,1].min()
max_of_study_hrs = X[:,0].max()
max_of_prev_exam = X[:,1].max()
print(f"Previous exam mean: {mean_prev_exam}")
print(f"Study hours mean: {study_hours_mean}")
print(f"Min of study hours: {min_of_study_hrs}")
print(f"Min of previous exam: {min_of_prev_exam}")
print(f"Max of study hours: {max_of_study_hrs}")
print(f"Max of previous exam: {max_of_prev_exam}")

Previous exam mean: 78.6
Study hours mean: 6.2
Min of study hours: 3
Min of previous exam: 65
Max of study hours: 9
Max of previous exam: 92


In [53]:
# compute predictions with formula: X @ + b 
# find highest and lowest prediction

predictions = X @ w + b
highest_prediction = predictions.max()
lowest_prediction = predictions.min()
print(f"Predictions: {predictions}")
print(f"Highest prediction: {highest_prediction}")
print(f"Lowest prediction: {lowest_prediction}")

Predictions: [60.5 77.1 91.9 61.5 86.6]
Highest prediction: 91.89999999999999
Lowest prediction: 60.5


In [71]:
# find predictions greater than or equal to 75
# print names and predictions of those students
# find the student with the highest prediction

pred_over_75 = predictions >= 75
highest_idx = predictions.argmax()
print(f"Predictions over 75: {predictions[pred_over_75]}")
print(f"Names of predictions over 75: {names[pred_over_75]}")
print(f"Highest Prediction: {names[highest_idx]} {highest_prediction:.2f}")

Predictions over 75: [77.1 91.9 86.6]
Names of predictions over 75: ['Bob' 'Charlie' 'Ethan']
Highest Prediction: Charlie 91.90


In [66]:
# compute the norm of each students feature vector

norms = np.linalg.norm(X,axis=1)
for name, norm in zip(names, norms):
    print(f"{name} {norm:.2f}")

Alice 65.12
Bob 78.31
Charlie 92.44
Dana 70.06
Ethan 88.36
